rootstock:
  action_ns: move_group
  arm_ip: 192.168.0.1
  arm_port: 8888
  group_name: right_arm
  base_link: base
  end_effector: right_gripper
  joint_names: [right_e0, right_e1, right_s0, right_s1, right_w0, right_w1, right_w2]
  
  init:
    joints:
    - [0.0, -1.68, 1.68, 0.0, 0.0, 0.0]
    poses:
    - - [0.786, -0.385, -0.124]
      - [1.430, -1.410, 1.885]
  feeder:
    grid: {X: 3, Y: 3, x_first: false, x_step: -0.05, y_step: 0.05}
    poses:
    - - [0.831, -0.098, -0.033]
      - [1.469, -1.413, 1.779]
  cut:
    poses:
    - - [0.571, 0.011, 0.020]
      - [1.413, -1.375, -3.106]
  clip:
    grid: {X: 1, Y: 1, x_first: true, x_step: 0.0, y_step: 0.0}
    poses:
    - - [0.695, 0.187, 0.106]
      - [1.009, -1.382, 3.051]
  inspection:
    poses:
    - - [0.755, -0.125, 0.002]
      - [0.224, 1.450, 0.878]
  dispense:
    grid: {X: 3, Y: 3, x_first: true, x_step: -0.05, y_step: -0.05}
    poses:
    - - [0.587, -0.750, -0.032]
      - [-0.983, 1.502, -2.385]
  reject:
    poses:
    - - [0.587, -0.750, -0.032]
      - [-0.983, 1.502, -2.385]
  input: {clipper: 4, conveyor: 3, cutter: 2, gripper: 1}
  output: {clipper: 4, conveyor: 3, cutter: 2, gripper: 1}
scion:
  action_ns: move_group
  arm_ip: 192.168.0.1
  arm_port: 8888
  base_link: base
  group_name: left_arm
  joint_names: [left_e0, left_e1, left_s0, left_s1, left_w0, left_w1, left_w2]
  end_effector: left_gripper
  init:
    joint: [0.0, -1.68, 1.68, 0.0, 0.0, 0.0]
    poses:
    - - [-0.377, 0.924, 0.019, 0.052]
      - [-3.137, 0.111, -2.366]
  feeder:
    grid: {X: 3, Y: 3, x_first: false, x_step: -0.05, y_step: 0.05}
    poses:
    - - [0.761, 0.472, 0.045]
      - [-0.113, 1.478, 0.156]
  cut:
    poses:
    - - [0.755, 0.249, -0.011]
      - [1.572, 1.473, 1.720]
  clip:
    poses:
    - - [0.544, 0.163, -0.033]
      - [2.050, 1.335, 0.634]
  input: {clipper: 4, conveyor: 3, cutter: 2, gripper: 1}
  output: {clipper: 4, conveyor: 3, cutter: 2, gripper: 1}
