rootstock:
  action_ns: move_group
  arm_ip: 192.168.0.1
  arm_port: 8888
  base_link: left_arm_base_link
  clip:
    grid: {X: 1, Y: 1, x_first: true, x_step: 0.0, y_step: 0.0}
    poses:
    - - [0.781, 0.174, 0.571]
      - [-0.0, 0.0, 1.487]
  cut:
    poses:
    - - [0.624, 0.346, 0.421]
      - [0.0, 0.0, 1.532]
  dispense:
    grid: {X: 1, Y: 1, x_first: true, x_step: -0.1, y_step: -0.1}
    poses:
    - - [0.659, -0.547, 0.27]
      - [-0.0, -0.0, -1.468]
  end_effector: left_arm_link_6
  feeder:
    grid: {X: 1, Y: 1, x_first: false, x_step: -0.1, y_step: 0.1}
    poses:
    - - [0.464, 0.524, 0.113]
      - [0.0, 0.0, 1.532]
  group_name: left_arm
  init:
    joints:
    - [0.0, -1.68, 1.68, 0.0, 0.0, 0.0]
    poses:
    - - [0.375, 0.0, 0.887]
      - [-0.0, 0.0, 0.0]
    - - [0.475, 0.0, 0.887]
      - [-0.0, 0.0, 0.0]
  input: {clipper: 4, conveyor: 3, cutter: 2, gripper: 1}
  inspection:
    poses:
    - - [0.734, -0.0, 0.281]
      - [0.0, 0.0, 0]
  joint_names: [left_arm_joint_a1, left_arm_joint_a2, left_arm_joint_a3, left_arm_joint_a4,
    left_arm_joint_a5, left_arm_joint_a6]
  output: {clipper: 4, conveyor: 3, cutter: 2, gripper: 1}
  reject:
    poses:
    - - [0.734, 0.0, 0.025]
      - [0.0, 0.0, 0]
scion:
  action_ns: righ_move_group
  arm_ip: 192.168.0.1
  arm_port: 8888
  base_link: right_arm_base_link
  clip:
    poses:
    - - [0.164, -0.425, 0.064]
      - [-0.0, -0.0, 3.098]
  cut:
    poses:
    - - [0.527, 0.003, 0.064]
      - [-0.038, -0.003, 0.013]
  end_effector: right_arm_link_6
  feeder:
    grid: {X: 1, Y: 1, x_first: true, x_step: -0.05, y_step: -0.05}
    poses:
    - - [0.592, 0.567, 0.298]
      - [0.0, 0.0, 1.639]
  group_name: right_arm
  init:
    joint: [0.0, -1.68, 1.68, 0.0, 0.0, 0.0]
    poses:
    - - [0.475, 0.0, 0.887]
      - [0.0, 0.0, 0.0]
  input: {clipper: 4, conveyor: 3, cutter: 2, gripper: 1}
  joint_names: [right_arm_joint_a1, right_arm_joint_a2, right_arm_joint_a3, right_arm_joint_a4,
    right_arm_joint_a5, right_arm_joint_a6]
  output: {clipper: 4, conveyor: 3, cutter: 2, gripper: 1}
