rootstock:
  arm_ip: 192.168.0.1
  arm_port: 8888
  feeder:
    pose: [[[0.302, 0.438, 0.435], [2.492, 1.570, -2.198]], [[0.297, 0.669, 0.435], [2.701, 1.570, -1.989]]] # pose wrt 
    grid:
      X: 2
      Y: 2
      x_step: -0.05
      y_step: -0.05
      x_first: true
  cut:
    pose: [[[0.475, -0.000, 0.887], [2.490, 1.571, 2.490]],[[0.692, -0.000, 0.887],[-1.281, 1.571, -1.281]]]  # x,y,z,r,p,y: the robot will go to each position before reaching the last
  clip:
    pose: [[[0.692, 0.000, 0.555],[0.218, 1.571, 0.219]]]
  dispose:
    pose: [[[0,0,0],[0,0,0]]]
  dispense:
    pose: [[[0.692, -0.369, 0.556], [-2.766, 1.571, -2.766]]] # pose wrt 
    grid:
      X: 2
      Y: 2
      x_step: -0.1
      y_step: 0.1
      x_first: false
  input:
    gripper: 1  # a plant is picked by the gripper
    cutter: 2   # cutter detects plant
    conveyor: 3 # plants are at the conveyor position
    clipper: 4  
  output:
    gripper: 1  # if active, gripper is closed. if not, is open
    cutter: 2   # if active, the cutter cuts.
    conveyor: 3 # if active, the conveyor moves
    clipper: 4  # if active, the clipper dispenses a clip

scion:
  arm_ip: 192.168.0.1
  arm_port: 8888
  feeder:
    pose: [[0, 0, 0, 0, 0, 0]] # pose wrt 
    grid:
      X: 2
      Y: 2
      x_step: 0.1
      y_step: 0.1
      x_first: true
  cut:
    pose: [[0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0]]  # x,y,z,r,p,y: the robot will go to each position before reaching the last
  clip:
    pose: [[0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0]]
  dispose:
    pose: [[0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0]]
  input:
    gripper: 1  # a plant is picked by the gripper
    cutter: 2   # cutter detects plant
    conveyor: 3 # plants are at the conveyor position
    clipper: 4  
  output:
    gripper: 1  # if active, gripper is closed. if not, is open
    cutter: 2   # if active, the cutter cuts.
    conveyor: 3 # if active, the conveyor moves
    clipper: 4  # if active, the clipper dispenses a clip

