controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_arm_joint_a1
      - left_arm_joint_a2
      - left_arm_joint_a3
      - left_arm_joint_a4
      - left_arm_joint_a5
      - left_arm_joint_a6
  - name: fake_right_arm_controller
    joints:
      - right_arm_joint_a1
      - right_arm_joint_a2
      - right_arm_joint_a3
      - right_arm_joint_a4
      - right_arm_joint_a5
      - right_arm_joint_a6
  - name: fake_left_eef_controller
    joints:
      []
  - name: fake_right_eef_controller
    joints:
      []
  - name: fake_both_arms_controller
    joints:
      - left_arm_joint_a1
      - left_arm_joint_a2
      - left_arm_joint_a3
      - left_arm_joint_a4
      - left_arm_joint_a5
      - left_arm_joint_a6
      - right_arm_joint_a1
      - right_arm_joint_a2
      - right_arm_joint_a3
      - right_arm_joint_a4
      - right_arm_joint_a5
      - right_arm_joint_a6