joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 125

right_arm_position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - right_arm_joint_a1
     - right_arm_joint_a2
     - right_arm_joint_a3
     - right_arm_joint_a4
     - right_arm_joint_a5
     - right_arm_joint_a6
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_arm_joint_a1: {trajectory: 0.1, goal: 0.1}
      right_arm_joint_a2: {trajectory: 0.1, goal: 0.1}
      right_arm_joint_a3: {trajectory: 0.1, goal: 0.1}
      right_arm_joint_a4: {trajectory: 0.1, goal: 0.1}
      right_arm_joint_a5: {trajectory: 0.1, goal: 0.1}
      right_arm_joint_a6: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10

left_arm_position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - left_arm_joint_a1
     - left_arm_joint_a2
     - left_arm_joint_a3
     - left_arm_joint_a4
     - left_arm_joint_a5
     - left_arm_joint_a6
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_arm_joint_a1: {trajectory: 0.1, goal: 0.1}
      left_arm_joint_a2: {trajectory: 0.1, goal: 0.1}
      left_arm_joint_a3: {trajectory: 0.1, goal: 0.1}
      left_arm_joint_a4: {trajectory: 0.1, goal: 0.1}
      left_arm_joint_a5: {trajectory: 0.1, goal: 0.1}
      left_arm_joint_a6: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10

coordinated_position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - right_arm_joint_a1
     - right_arm_joint_a2
     - right_arm_joint_a3
     - right_arm_joint_a4
     - right_arm_joint_a5
     - right_arm_joint_a6
     - left_arm_joint_a1
     - left_arm_joint_a2
     - left_arm_joint_a3
     - left_arm_joint_a4
     - left_arm_joint_a5
     - left_arm_joint_a6
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_arm_joint_a1: {trajectory: 0.1, goal: 0.1}
      right_arm_joint_a2: {trajectory: 0.1, goal: 0.1}
      right_arm_joint_a3: {trajectory: 0.1, goal: 0.1}
      right_arm_joint_a4: {trajectory: 0.1, goal: 0.1}
      right_arm_joint_a5: {trajectory: 0.1, goal: 0.1}
      right_arm_joint_a6: {trajectory: 0.1, goal: 0.1}
      left_arm_joint_a1: {trajectory: 0.1, goal: 0.1}
      left_arm_joint_a2: {trajectory: 0.1, goal: 0.1}
      left_arm_joint_a3: {trajectory: 0.1, goal: 0.1}
      left_arm_joint_a4: {trajectory: 0.1, goal: 0.1}
      left_arm_joint_a5: {trajectory: 0.1, goal: 0.1}
      left_arm_joint_a6: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10
